// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qoucqynhazbhkrfzwhfi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvdWNxeW5oYXpiaGtyZnp3aGZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1Mzk4NTIsImV4cCI6MjA2MjExNTg1Mn0.c-KmItazWxWDTaSEkCh_zuidClcfYZ2Bi9TDNrNSbnk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);